[build]
  publish = "out"
  command = "yarn run build-prod"

[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"  
  CONTRACT_ADDRESS = "pizza"  

