[build]
  publish = "out"
  command = "yarn run build-prod"

[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"  
  NEXT_PUBLIC_CONTRACT_ID = "ADD_CONTRACT_ADDRESS_HERE"  
  NEXT_PUBLIC_NETWORK_ID = "ADD_NETWORK_ID"  
  NEXT_PUBLIC_NETWORK_NAME = "ADD_NETWORK_NAME"  
  NEXT_PUBLIC_PINATA_API_KEY = "ADD_PINATA_API_KEY"  
  NEXT_PUBLIC_PINATA_API_SECRET = "ADD_PINATA_API_SECRET_HERE"  
